winget install Bitwarden.Bitwarden
winget install JanDeDobbeleer.OhMyPosh -s winget
winget install Git.Git
winget install GitKraken
winget install JGraph.Draw
winget install Notepad++.Notepad++
winget install Microsoft.VisualStudioCode
winget install Microsoft.DotNet.SDK.8
winget install Microsoft.OpenJDK.21
winget install JetBrains.Toolbox
winget install dotPDN.PaintDotNet
winget install Postman.Postman
winget install Bruno.Bruno
winget install Microsoft.AzureCLI
winget install Amazon.AWSCLI
winget install Mozilla.FireFox
winget install Proton.ProtonVPN
winget install Proton.ProtonDrive
winget install Docker.DockerDesktop
winget install Microsoft.SQLServerManagementStudio
winget install Microsoft.VisualStudio.2022.Community
